import React from "react";
import { 
  FileX2, Scissors, Trash2, RotateCw, Droplets, 
  Minimize, Maximize, Shield, FileText, File, 
  FileImage, FileSpreadsheet, Image, BookOpen,
  Zap, Palette, Files, Hash, Edit, Unlock, 
  ArrowUpDown, Info, Braces, Presentation, Key,
  Settings, Code, Monitor, ListOrdered, Shuffle
} from "lucide-react";

export interface ToolConfig {
  id: string;
  title: string;
  description: string;
  icon: string;
  iconColor: string;
  bgColor: string;
  path: string;
  metaTitle: string;
  metaDescription: string;
  acceptedFiles: string;
  category: 'core' | 'converter';
}

export const toolsConfig: Record<string, ToolConfig> = {
  'merge-pdf': {
    id: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    icon: 'Files',
    iconColor: 'text-white',
    bgColor: 'bg-blue-600 hover:bg-blue-700',
    path: '/merge-pdf',
    metaTitle: 'Merge PDF Files Online - Free PDF Merger | PDFo',
    metaDescription: 'Combine multiple PDF files into one document easily. Free online PDF merger tool with drag-and-drop support.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'split-pdf': {
    id: 'split-pdf',
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    icon: 'Scissors',
    iconColor: 'text-white',
    bgColor: 'bg-orange-600 hover:bg-orange-700',
    path: '/split-pdf',
    metaTitle: 'Split PDF Files Online - Free PDF Splitter | PDFo',
    metaDescription: 'Split PDF documents into separate pages or extract specific pages. Fast and secure online PDF splitter.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'delete-pdf-pages': {
    id: 'delete-pdf-pages',
    title: 'Delete PDF Pages',
    description: 'Remove unwanted pages from your PDF documents quickly and easily.',
    icon: 'Trash2',
    iconColor: 'text-white',
    bgColor: 'bg-red-600 hover:bg-red-700',
    path: '/delete-pdf-pages',
    metaTitle: 'Delete PDF Pages Online - Remove PDF Pages | PDFo',
    metaDescription: 'Remove unwanted pages from PDF documents. Select and delete specific pages from your PDF files online.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'rotate-pdf': {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!',
    icon: 'RotateCw',
    iconColor: 'text-white',
    bgColor: 'bg-purple-600 hover:bg-purple-700',
    path: '/rotate-pdf',
    metaTitle: 'Rotate PDF Online - Free PDF Rotator | PDFo',
    metaDescription: 'Rotate PDF pages clockwise or counterclockwise. Fix orientation of PDF documents online for free.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'watermark-pdf': {
    id: 'watermark-pdf',
    title: 'Watermark PDF',
    description: 'Add watermarks to your PDF documents to protect your intellectual property.',
    icon: 'Droplets',
    iconColor: 'text-white',
    bgColor: 'bg-teal-600 hover:bg-teal-700',
    path: '/watermark-pdf',
    metaTitle: 'Add Watermark to PDF Online - PDF Watermarker | PDFo',
    metaDescription: 'Add text or image watermarks to PDF documents. Protect your PDFs with custom watermarks online.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'page-numbers-pdf': {
    id: 'page-numbers-pdf',
    title: 'Page Numbers',
    description: 'Add page numbers to your PDF documents for better organization.',
    icon: 'Palette',
    iconColor: 'text-white',
    bgColor: 'bg-indigo-600 hover:bg-indigo-700',
    path: '/page-numbers-pdf',
    metaTitle: 'Add Page Numbers to PDF Online - PDF Page Numbering | PDFo',
    metaDescription: 'Add page numbers to PDF documents with custom formatting. Number PDF pages online for free.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'pdf-editor': {
    id: 'pdf-editor',
    title: 'PDF Editor',
    description: 'Add text, images, shapes, and annotations to your PDF documents.',
    icon: 'Zap',
    iconColor: 'text-white',
    bgColor: 'bg-green-600 hover:bg-green-700',
    path: '/pdf-editor',
    metaTitle: 'Edit PDF Online - Free PDF Editor | PDFo',
    metaDescription: 'Edit PDF documents online. Add text, images, shapes, and annotations to your PDF files.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'pdf-to-jpg': {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    description: 'Convert each PDF page into a JPG or extract all images contained in a PDF.',
    icon: 'FileImage',
    iconColor: 'text-white',
    bgColor: 'bg-yellow-600 hover:bg-yellow-700',
    path: '/pdf-to-jpg',
    metaTitle: 'Convert PDF to JPG Online - PDF to Image Converter | PDFo',
    metaDescription: 'Convert PDF pages to JPG images online. Extract images from PDF documents with high quality.',
    acceptedFiles: '.pdf',
    category: 'converter',
  },
  'pdf-to-png': {
    id: 'pdf-to-png',
    title: 'PDF to PNG',
    description: 'Convert PDF pages to high-quality PNG images with transparency support.',
    icon: 'Image',
    iconColor: 'text-white',
    bgColor: 'bg-pink-600 hover:bg-pink-700',
    path: '/pdf-to-png',
    metaTitle: 'Convert PDF to PNG Online - PDF to PNG Converter | PDFo',
    metaDescription: 'Convert PDF pages to PNG images with transparency support. High-quality PDF to PNG conversion online.',
    acceptedFiles: '.pdf',
    category: 'converter',
  },
  'pdf-to-tiff': {
    id: 'pdf-to-tiff',
    title: 'PDF to TIFF',
    description: 'Convert PDF documents to high-quality TIFF image format.',
    icon: 'FileImage',
    iconColor: 'text-white',
    bgColor: 'bg-cyan-600 hover:bg-cyan-700',
    path: '/pdf-to-tiff',
    metaTitle: 'Convert PDF to TIFF Online - PDF to TIFF Converter | PDFo',
    metaDescription: 'Convert PDF documents to TIFF images online. High-quality PDF to TIFF conversion with multiple pages support.',
    acceptedFiles: '.pdf',
    category: 'converter',
  },
  'pdf-to-json': {
    id: 'pdf-to-json',
    title: 'PDF to JSON',
    description: 'Extract structured data from PDF documents in JSON format.',
    icon: 'Zap',
    iconColor: 'text-white',
    bgColor: 'bg-slate-600 hover:bg-slate-700',
    path: '/pdf-to-json',
    metaTitle: 'Convert PDF to JSON Online - Extract PDF Data | PDFo',
    metaDescription: 'Extract structured data from PDF documents in JSON format. Convert PDF content to machine-readable JSON.',
    acceptedFiles: '.pdf',
    category: 'converter',
  },
  'pdf-to-word': {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Convert PDF files into editable Word documents. The best quality PDF to Word conversion.',
    icon: 'FileText',
    iconColor: 'text-white',
    bgColor: 'bg-blue-700 hover:bg-blue-800',
    path: '/pdf-to-word',
    metaTitle: 'Convert PDF to Word Online - PDF to DOC Converter | PDFo',
    metaDescription: 'Convert PDF files to editable Word documents online. Best quality PDF to Word conversion with formatting preserved.',
    acceptedFiles: '.pdf',
    category: 'converter',
  },
  'pdf-to-ppt': {
    id: 'pdf-to-ppt',
    title: 'PDF to PPT',
    description: 'Turn your PDF files into editable PowerPoint presentations.',
    icon: 'File',
    iconColor: 'text-white',
    bgColor: 'bg-red-700 hover:bg-red-800',
    path: '/pdf-to-ppt',
    metaTitle: 'Convert PDF to PowerPoint Online - PDF to PPT Converter | PDFo',
    metaDescription: 'Convert PDF files to PowerPoint presentations online. Transform PDF documents into editable PPT slides.',
    acceptedFiles: '.pdf',
    category: 'converter',
  },
  'pdf-to-txt': {
    id: 'pdf-to-txt',
    title: 'PDF to TXT',
    description: 'Extract text content from PDF documents as plain text files.',
    icon: 'FileText',
    iconColor: 'text-white',
    bgColor: 'bg-gray-600 hover:bg-gray-700',
    path: '/pdf-to-txt',
    metaTitle: 'Convert PDF to Text Online - PDF to TXT Converter | PDFo',
    metaDescription: 'Extract text from PDF documents online. Convert PDF content to plain text files for easy editing.',
    acceptedFiles: '.pdf',
    category: 'converter',
  },
  'pdf-to-excel': {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Convert PDF files to Excel spreadsheets. Perfect for data analysis.',
    icon: 'FileSpreadsheet',
    iconColor: 'text-white',
    bgColor: 'bg-green-700 hover:bg-green-800',
    path: '/pdf-to-excel',
    metaTitle: 'Convert PDF to Excel Online - PDF to XLS Converter | PDFo',
    metaDescription: 'Convert PDF files to Excel spreadsheets online. Extract tables and data from PDF to Excel format.',
    acceptedFiles: '.pdf',
    category: 'converter',
  },
  'png-to-pdf': {
    id: 'png-to-pdf',
    title: 'PNG to PDF',
    description: 'Convert PNG images to PDF documents. Combine multiple images into one PDF.',
    icon: 'File',
    iconColor: 'text-white',
    bgColor: 'bg-purple-700 hover:bg-purple-800',
    path: '/png-to-pdf',
    metaTitle: 'Convert PNG to PDF Online - Image to PDF Converter | PDFo',
    metaDescription: 'Convert PNG images to PDF documents online. Combine multiple PNG files into a single PDF.',
    acceptedFiles: '.png',
    category: 'converter',
  },
  'word-to-pdf': {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Convert Word documents to PDF format while preserving the original formatting.',
    icon: 'BookOpen',
    iconColor: 'text-white',
    bgColor: 'bg-blue-800 hover:bg-blue-900',
    path: '/word-to-pdf',
    metaTitle: 'Convert Word to PDF Online - DOC to PDF Converter | PDFo',
    metaDescription: 'Convert Word documents to PDF online. Transform DOC and DOCX files to PDF with original formatting.',
    acceptedFiles: '.doc,.docx',
    category: 'converter',
  },
  'lock-pdf': {
    id: 'lock-pdf',
    title: 'Lock PDF',
    description: 'Add password protection to your PDF documents to secure them from unauthorized access.',
    icon: 'Shield',
    iconColor: 'text-white',
    bgColor: 'bg-red-600 hover:bg-red-700',
    path: '/lock-pdf',
    metaTitle: 'Lock PDF with Password Online - Secure PDF Documents | PDFo',
    metaDescription: 'Add password protection to PDF files online. Secure your PDF documents with encryption and password protection.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'unlock-pdf': {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    description: 'Remove password protection from PDF documents that you own.',
    icon: 'FileX2',
    iconColor: 'text-white',
    bgColor: 'bg-green-600 hover:bg-green-700',
    path: '/unlock-pdf',
    metaTitle: 'Unlock PDF Online - Remove PDF Password Protection | PDFo',
    metaDescription: 'Remove password protection from PDF files online. Unlock encrypted PDF documents quickly and securely.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'compress-pdf': {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining document quality and readability.',
    icon: 'Minimize',
    iconColor: 'text-white',
    bgColor: 'bg-amber-600 hover:bg-amber-700',
    path: '/compress-pdf',
    metaTitle: 'Compress PDF Online - Reduce PDF File Size | PDFo',
    metaDescription: 'Compress PDF files online to reduce file size while maintaining quality. Free PDF compression tool.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'reorder-pages': {
    id: 'reorder-pages',
    title: 'Reorder Pages',
    description: 'Rearrange and reorganize the order of pages in your PDF documents.',
    icon: 'Files',
    iconColor: 'text-white',
    bgColor: 'bg-violet-600 hover:bg-violet-700',
    path: '/reorder-pages',
    metaTitle: 'Reorder PDF Pages Online - Rearrange PDF Pages | PDFo',
    metaDescription: 'Rearrange and reorder pages in PDF documents online. Organize your PDF pages in any order you want.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'edit-metadata': {
    id: 'edit-metadata',
    title: 'Edit Metadata',
    description: 'Modify PDF properties like title, author, subject, and keywords.',
    icon: 'FileText',
    iconColor: 'text-white',
    bgColor: 'bg-slate-600 hover:bg-slate-700',
    path: '/edit-metadata',
    metaTitle: 'Edit PDF Metadata Online - Modify PDF Properties | PDFo',
    metaDescription: 'Edit PDF metadata and properties online. Change title, author, subject, and keywords of PDF documents.',
    acceptedFiles: '.pdf',
    category: 'core',
  },
  'excel-to-pdf': {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF format while preserving formatting and layout.',
    icon: 'FileSpreadsheet',
    iconColor: 'text-white',
    bgColor: 'bg-emerald-600 hover:bg-emerald-700',
    path: '/excel-to-pdf',
    metaTitle: 'Convert Excel to PDF Online - XLS to PDF Converter | PDFo',
    metaDescription: 'Convert Excel files to PDF online. Transform XLS and XLSX spreadsheets to PDF with original formatting.',
    acceptedFiles: '.xls,.xlsx',
    category: 'converter',
  },
};

export const getToolConfig = (toolType: string): ToolConfig | undefined => {
  return toolsConfig[toolType];
};

export const getAllTools = (): ToolConfig[] => {
  return Object.values(toolsConfig);
};

export const getToolsByCategory = (category: 'core' | 'converter'): ToolConfig[] => {
  return Object.values(toolsConfig).filter(tool => tool.category === category);
};

export const getToolIcon = (toolId: string, colorClass: string) => {
  const iconMap: Record<string, React.ComponentType<any>> = {
    'merge-pdf': Files,
    'split-pdf': Scissors,
    'delete-pdf-pages': Trash2,
    'rotate-pdf': RotateCw,
    'watermark-pdf': Droplets,
    'page-numbers-pdf': Hash,
    'pdf-editor': Edit,
    'pdf-to-jpg': FileImage,
    'pdf-to-png': Image,
    'pdf-to-tiff': FileImage,
    'pdf-to-json': Braces,
    'pdf-to-word': FileText,
    'pdf-to-ppt': Presentation,
    'pdf-to-txt': FileText,
    'pdf-to-excel': FileSpreadsheet,
    'png-to-pdf': FileImage,
    'word-to-pdf': BookOpen,
    'lock-pdf': Shield,
    'unlock-pdf': Unlock,
    'compress-pdf': Minimize,
    'reorder-pages': ArrowUpDown,
    'edit-metadata': Settings,
    'excel-to-pdf': FileSpreadsheet,
  };
  
  const IconComponent = iconMap[toolId] || File;
  return React.createElement(IconComponent, { className: `h-8 w-8 ${colorClass}` });
};
