import React from "react";
import { 
  FileX2, Scissors, Trash2, RotateCw, Droplets, 
  Minimize, Maximize, Shield, FileText, File, 
  FileImage, FileSpreadsheet, Image, BookOpen,
  Zap, Palette, Files, Hash, Edit, Unlock, 
  ArrowUpDown, Info, Braces, Presentation, Key,
  Settings, Code, Monitor, ListOrdered, Shuffle
} from "lucide-react";

export interface ToolConfig {
  id: string;
  title: string;
  description: string;
  icon: string;
  iconColor: string;
  bgColor: string;
  path: string;
  metaTitle: string;
  metaDescription: string;
  acceptedFiles: string;
  category: 'organize' | 'edit' | 'security' | 'conversion' | 'other';
  order: number;
}

export const toolsConfig: Record<string, ToolConfig> = {
  // Organize Tools (1-7)
  'merge-pdf': {
    id: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
    icon: 'Files',
    iconColor: 'text-white',
    bgColor: 'bg-blue-600 hover:bg-blue-700',
    path: '/merge-pdf',
    metaTitle: 'Merge PDF Files Online - Free PDF Merger | PDFo',
    metaDescription: 'Combine multiple PDF files into one document easily. Free online PDF merger tool with drag-and-drop support.',
    acceptedFiles: '.pdf',
    category: 'organize',
    order: 1,
  },
  'split-pdf': {
    id: 'split-pdf',
    title: 'Split PDF',
    description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
    icon: 'Scissors',
    iconColor: 'text-white',
    bgColor: 'bg-orange-600 hover:bg-orange-700',
    path: '/split-pdf',
    metaTitle: 'Split PDF Files Online - Free PDF Splitter | PDFo',
    metaDescription: 'Split PDF documents into separate pages or extract specific pages. Fast and secure online PDF splitter.',
    acceptedFiles: '.pdf',
    category: 'organize',
    order: 2,
  },
  'reorder-pages': {
    id: 'reorder-pages',
    title: 'Reorder Pages',
    description: 'Reorganize PDF pages in any order. Drag and drop pages to rearrange your document.',
    icon: 'ArrowUpDown',
    iconColor: 'text-white',
    bgColor: 'bg-indigo-600 hover:bg-indigo-700',
    path: '/reorder-pages',
    metaTitle: 'Reorder PDF Pages Online - Rearrange PDF Pages | PDFo',
    metaDescription: 'Easily reorder and rearrange PDF pages online. Drag and drop interface for quick page reorganization.',
    acceptedFiles: '.pdf',
    category: 'organize',
    order: 3,
  },
  'delete-pdf-pages': {
    id: 'delete-pdf-pages',
    title: 'Delete Pages',
    description: 'Remove unwanted pages from your PDF documents quickly and easily.',
    icon: 'Trash2',
    iconColor: 'text-white',
    bgColor: 'bg-red-600 hover:bg-red-700',
    path: '/delete-pdf-pages',
    metaTitle: 'Delete PDF Pages Online - Remove PDF Pages | PDFo',
    metaDescription: 'Remove unwanted pages from PDF files online. Select and delete specific pages from your PDF documents.',
    acceptedFiles: '.pdf',
    category: 'organize',
    order: 4,
  },
  'rotate-pdf': {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate your PDF pages. Rotate all pages or just specific ones.',
    icon: 'RotateCw',
    iconColor: 'text-white',
    bgColor: 'bg-green-600 hover:bg-green-700',
    path: '/rotate-pdf',
    metaTitle: 'Rotate PDF Pages Online - Free PDF Rotator | PDFo',
    metaDescription: 'Rotate PDF pages online for free. Fix orientation of your PDF documents with our easy-to-use tool.',
    acceptedFiles: '.pdf',
    category: 'organize',
    order: 5,
  },
  'page-numbers-pdf': {
    id: 'page-numbers-pdf',
    title: 'Page Numbers',
    description: 'Add page numbers to your PDF. Choose position, format and starting number.',
    icon: 'Hash',
    iconColor: 'text-white',
    bgColor: 'bg-purple-600 hover:bg-purple-700',
    path: '/page-numbers-pdf',
    metaTitle: 'Add Page Numbers to PDF Online | PDFo',
    metaDescription: 'Add page numbers to PDF documents online. Customize position, format, and starting number for your PDF pages.',
    acceptedFiles: '.pdf',
    category: 'organize',
    order: 6,
  },
  'edit-metadata': {
    id: 'edit-metadata',
    title: 'Edit Metadata',
    description: 'Edit PDF metadata including title, author, subject, and keywords.',
    icon: 'Settings',
    iconColor: 'text-white',
    bgColor: 'bg-gray-600 hover:bg-gray-700',
    path: '/edit-metadata',
    metaTitle: 'Edit PDF Metadata Online - Change PDF Properties | PDFo',
    metaDescription: 'Edit PDF metadata and properties online. Change title, author, subject, and other document information.',
    acceptedFiles: '.pdf',
    category: 'organize',
    order: 7,
  },

  // Edit Tools (8-9)
  'watermark-pdf': {
    id: 'watermark-pdf',
    title: 'Watermark PDF',
    description: 'Add text or image watermarks to your PDF documents for branding or security.',
    icon: 'Droplets',
    iconColor: 'text-white',
    bgColor: 'bg-cyan-600 hover:bg-cyan-700',
    path: '/watermark-pdf',
    metaTitle: 'Add Watermark to PDF Online - PDF Watermarking Tool | PDFo',
    metaDescription: 'Add watermarks to PDF files online. Insert text or image watermarks for branding and document protection.',
    acceptedFiles: '.pdf',
    category: 'edit',
    order: 8,
  },
  'pdf-editor': {
    id: 'pdf-editor',
    title: 'PDF Editor',
    description: 'Edit PDF content directly. Add text, images, and annotations to your documents.',
    icon: 'Edit',
    iconColor: 'text-white',
    bgColor: 'bg-yellow-600 hover:bg-yellow-700',
    path: '/pdf-editor',
    metaTitle: 'Edit PDF Online - Free PDF Editor | PDFo',
    metaDescription: 'Edit PDF files online with our comprehensive PDF editor. Add text, images, and annotations easily.',
    acceptedFiles: '.pdf',
    category: 'edit',
    order: 9,
  },

  // Security & Optimization Tools (10-12)
  'lock-pdf': {
    id: 'lock-pdf',
    title: 'Lock PDF',
    description: 'Protect your PDF with password encryption and restrict access permissions.',
    icon: 'Shield',
    iconColor: 'text-white',
    bgColor: 'bg-red-700 hover:bg-red-800',
    path: '/lock-pdf',
    metaTitle: 'Password Protect PDF Online - Lock PDF Files | PDFo',
    metaDescription: 'Password protect PDF files online. Add security and restrict access to your important documents.',
    acceptedFiles: '.pdf',
    category: 'security',
    order: 10,
  },
  'unlock-pdf': {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    description: 'Remove password protection from PDF files. Unlock encrypted PDF documents.',
    icon: 'Unlock',
    iconColor: 'text-white',
    bgColor: 'bg-green-700 hover:bg-green-800',
    path: '/unlock-pdf',
    metaTitle: 'Unlock PDF Online - Remove PDF Password | PDFo',
    metaDescription: 'Unlock password-protected PDF files online. Remove restrictions and access your PDF documents.',
    acceptedFiles: '.pdf',
    category: 'security',
    order: 11,
  },
  'compress-pdf': {
    id: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality. Optimize PDFs for sharing and storage.',
    icon: 'Minimize',
    iconColor: 'text-white',
    bgColor: 'bg-teal-600 hover:bg-teal-700',
    path: '/compress-pdf',
    metaTitle: 'Compress PDF Online - Reduce PDF File Size | PDFo',
    metaDescription: 'Compress PDF files online to reduce file size. Optimize PDFs while maintaining quality for easy sharing.',
    acceptedFiles: '.pdf',
    category: 'security',
    order: 12,
  },

  // Conversion Tools (13-20)
  'pdf-to-jpg': {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    description: 'Convert PDF pages to high-quality JPG images. Perfect for presentations and web use.',
    icon: 'FileImage',
    iconColor: 'text-white',
    bgColor: 'bg-pink-600 hover:bg-pink-700',
    path: '/pdf-to-jpg',
    metaTitle: 'Convert PDF to JPG Online - PDF to Image Converter | PDFo',
    metaDescription: 'Convert PDF to JPG images online. Transform PDF pages into high-quality JPG files for easy sharing.',
    acceptedFiles: '.pdf',
    category: 'conversion',
    order: 13,
  },
  'pdf-to-png': {
    id: 'pdf-to-png',
    title: 'PDF to PNG',
    description: 'Convert PDF pages to PNG images with transparent backgrounds. High-quality conversion.',
    icon: 'Image',
    iconColor: 'text-white',
    bgColor: 'bg-violet-600 hover:bg-violet-700',
    path: '/pdf-to-png',
    metaTitle: 'Convert PDF to PNG Online - PDF to PNG Converter | PDFo',
    metaDescription: 'Convert PDF to PNG images online. Get high-quality PNG files with transparent background support.',
    acceptedFiles: '.pdf',
    category: 'conversion',
    order: 14,
  },
  'pdf-to-tiff': {
    id: 'pdf-to-tiff',
    title: 'PDF to TIFF',
    description: 'Convert PDF to TIFF format for professional printing and archival purposes.',
    icon: 'FileImage',
    iconColor: 'text-white',
    bgColor: 'bg-rose-600 hover:bg-rose-700',
    path: '/pdf-to-tiff',
    metaTitle: 'Convert PDF to TIFF Online - PDF to TIFF Converter | PDFo',
    metaDescription: 'Convert PDF to TIFF format online. Professional quality conversion for printing and archival needs.',
    acceptedFiles: '.pdf',
    category: 'conversion',
    order: 15,
  },
  'pdf-to-word': {
    id: 'pdf-to-word',
    title: 'PDF to Word',
    description: 'Convert PDF to editable Word documents. Maintain formatting and layout.',
    icon: 'FileText',
    iconColor: 'text-white',
    bgColor: 'bg-blue-700 hover:bg-blue-800',
    path: '/pdf-to-word',
    metaTitle: 'Convert PDF to Word Online - PDF to DOCX Converter | PDFo',
    metaDescription: 'Convert PDF to Word documents online. Transform PDFs into editable DOCX files while preserving formatting.',
    acceptedFiles: '.pdf',
    category: 'conversion',
    order: 16,
  },
  'pdf-to-excel': {
    id: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Extract tables and data from PDF to Excel spreadsheets. Perfect for data analysis.',
    icon: 'FileSpreadsheet',
    iconColor: 'text-white',
    bgColor: 'bg-emerald-600 hover:bg-emerald-700',
    path: '/pdf-to-excel',
    metaTitle: 'Convert PDF to Excel Online - PDF to XLSX Converter | PDFo',
    metaDescription: 'Convert PDF to Excel spreadsheets online. Extract tables and data from PDFs into editable XLSX files.',
    acceptedFiles: '.pdf',
    category: 'conversion',
    order: 17,
  },
  'pdf-to-ppt': {
    id: 'pdf-to-ppt',
    title: 'PDF to PPT',
    description: 'Convert PDF pages to PowerPoint presentation slides. Perfect for editing and presenting.',
    icon: 'Presentation',
    iconColor: 'text-white',
    bgColor: 'bg-orange-700 hover:bg-orange-800',
    path: '/pdf-to-ppt',
    metaTitle: 'Convert PDF to PowerPoint Online - PDF to PPT Converter | PDFo',
    metaDescription: 'Convert PDF to PowerPoint presentations online. Transform PDF pages into editable PPT slides.',
    acceptedFiles: '.pdf',
    category: 'conversion',
    order: 18,
  },
  'pdf-to-txt': {
    id: 'pdf-to-txt',
    title: 'PDF to TXT',
    description: 'Extract plain text from PDF documents. Clean text extraction for further processing.',
    icon: 'FileText',
    iconColor: 'text-white',
    bgColor: 'bg-slate-600 hover:bg-slate-700',
    path: '/pdf-to-txt',
    metaTitle: 'Convert PDF to Text Online - PDF to TXT Converter | PDFo',
    metaDescription: 'Extract text from PDF files online. Convert PDF content to plain text format for easy editing.',
    acceptedFiles: '.pdf',
    category: 'conversion',
    order: 19,
  },
  'pdf-to-json': {
    id: 'pdf-to-json',
    title: 'PDF to JSON',
    description: 'Convert PDF content to structured JSON format. Perfect for data processing and APIs.',
    icon: 'Braces',
    iconColor: 'text-white',
    bgColor: 'bg-amber-600 hover:bg-amber-700',
    path: '/pdf-to-json',
    metaTitle: 'Convert PDF to JSON Online - PDF to JSON Converter | PDFo',
    metaDescription: 'Convert PDF to JSON format online. Extract structured data from PDFs for API integration and processing.',
    acceptedFiles: '.pdf',
    category: 'conversion',
    order: 20,
  },

  // Other Formats to PDF (21-23)
  'png-to-pdf': {
    id: 'png-to-pdf',
    title: 'PNG to PDF',
    description: 'Convert PNG images to PDF format. Combine multiple images into a single PDF.',
    icon: 'FileImage',
    iconColor: 'text-white',
    bgColor: 'bg-lime-600 hover:bg-lime-700',
    path: '/png-to-pdf',
    metaTitle: 'Convert PNG to PDF Online - Image to PDF Converter | PDFo',
    metaDescription: 'Convert PNG images to PDF online. Combine multiple PNG files into a single PDF document.',
    acceptedFiles: '.png,.jpg,.jpeg',
    category: 'other',
    order: 21,
  },
  'word-to-pdf': {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Convert Word documents to PDF format. Preserve formatting and ensure compatibility.',
    icon: 'BookOpen',
    iconColor: 'text-white',
    bgColor: 'bg-sky-600 hover:bg-sky-700',
    path: '/word-to-pdf',
    metaTitle: 'Convert Word to PDF Online - DOCX to PDF Converter | PDFo',
    metaDescription: 'Convert Word documents to PDF online. Transform DOCX files to PDF while preserving formatting.',
    acceptedFiles: '.doc,.docx',
    category: 'other',
    order: 22,
  },
  'excel-to-pdf': {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF format. Perfect for sharing and printing.',
    icon: 'FileSpreadsheet',
    iconColor: 'text-white',
    bgColor: 'bg-green-700 hover:bg-green-800',
    path: '/excel-to-pdf',
    metaTitle: 'Convert Excel to PDF Online - XLSX to PDF Converter | PDFo',
    metaDescription: 'Convert Excel spreadsheets to PDF online. Transform XLSX files into professional PDF documents.',
    acceptedFiles: '.xls,.xlsx',
    category: 'other',
    order: 23,
  },
};

export const getToolConfig = (toolType: string): ToolConfig | undefined => {
  return toolsConfig[toolType];
};

export const getAllTools = (): ToolConfig[] => {
  return Object.values(toolsConfig).sort((a, b) => a.order - b.order);
};

export const getToolsByCategory = (category: 'organize' | 'edit' | 'security' | 'conversion' | 'other'): ToolConfig[] => {
  return Object.values(toolsConfig)
    .filter(tool => tool.category === category)
    .sort((a, b) => a.order - b.order);
};

export const getToolIcon = (toolId: string, colorClass: string) => {
  const iconMap: Record<string, React.ComponentType<any>> = {
    'merge-pdf': Files,
    'split-pdf': Scissors,
    'delete-pdf-pages': Trash2,
    'rotate-pdf': RotateCw,
    'watermark-pdf': Droplets,
    'page-numbers-pdf': Hash,
    'pdf-editor': Edit,
    'pdf-to-jpg': FileImage,
    'pdf-to-png': Image,
    'pdf-to-tiff': FileImage,
    'pdf-to-json': Braces,
    'pdf-to-word': FileText,
    'pdf-to-ppt': Presentation,
    'pdf-to-txt': FileText,
    'pdf-to-excel': FileSpreadsheet,
    'png-to-pdf': FileImage,
    'word-to-pdf': BookOpen,
    'lock-pdf': Shield,
    'unlock-pdf': Unlock,
    'compress-pdf': Minimize,
    'reorder-pages': ArrowUpDown,
    'edit-metadata': Settings,
    'excel-to-pdf': FileSpreadsheet,
  };
  
  const IconComponent = iconMap[toolId] || File;
  return React.createElement(IconComponent, { className: `h-8 w-8 ${colorClass}` });
};